.
.TH "VSWITCH" "" "November 2018" "" ""
.

.SH "NAME"
	\fBvswitch\fR - disable all non-tunneled connections as a failsafe in the event of VPN disconnect.
.
.SH "SYNOPSIS"
	\fBvswitch [options] [arguments]\fR
.
.SH "DESCRIPTION"
 	\fBvswitch\fR is a lightweight manager for, VPN provider specific, OpenVPN connection settings. \fBvswitch\fR, when enabled, blocks all outgoing un-tunneled communications. Default tunnel is tun0. The state of \fBvswitch\fR's firewall is persistent through reboot - you will need to run \fBvswitch off\fR each time you wish to deactivate the killswitch regardless of system shutdowns.


.SH "OPTIONS"
\fBdistrobution\fR
.IP "" 4
(\fBos\fR) Declare which Linux distrobution is in use. Default = Solus.
.TP
\fBhelp\fR
.IP "" 4
(\fB/?\fR) Display this man page
.TP
\fBhost\fR [argument]
.IP "" 4
Change your VPN host/provider. Defaults to \fBnordvpn\fR
.TP
\fBipversion\fR [argument]
.IP "" 4
(\fBipv\fR) Change the version of internet protocols used to connect (\fB4\fR or \fB6\fR). Defaults to IPv\fB4\fR
.TP
\fBon\fR
.IP "" 4
(\fBenable\fR) Enable killswitch. All non-VPN connections will fail.
.TP
\fBoff\fR
.IP "" 4
(\fBdisable\fR) Disable killswitch. All traffic will be permitted.
.TP
\fBpanic\fR
.IP "" 4
(\fBpan\fR) Kill all incoming and all outgoing traffic. This can be reverted with \fBunpanic\fR whereby \fBvswitch\fR will enter a standard killswitch-enabled state.
.TP
\fBprotocol\fR [argument]
.IP "" 4
(\fBpr\fR) Change the protocol used to connect to VPN (\fBudp\fR or \fBtcp\fR). Changes take effect during next connection. Defaults to \fBudp\fR
.TP
\fBrecommend\fR [argument]
.IP "" 4
(\fBrec\fR) (\fBlist\fR) List the top recommended servers
.TP
\fBregion\fR [argument]
.IP "" 4
(\fBlocation\fR) Declare a 2-digit ISO country code as a preferential connection. Default = "us", use "clear" to remove preferences.
.TP
\fBremove\fR
.IP "" 4
(\fBrm\fR) Uninstall \fBvswitch\fR from your device
.TP
\fBstatus\fR
.IP "" 4
Check if the killswitch is enabled (blocking traffic) or disabled (allowing all traffic)
.TP
\fBunpanic\fR
.IP "" 4
Return \fBvswitch\fR to a standard killswitch-enabled state. From here you may run \fBvswitch off\fR to return to a non-VPN enabled state. See also: \fBpanic\fR
.TP
\fBupdate\fR
.IP "" 4
(\fBup\fR) Update the list of servers provided by your VPN host
.TP
\fBwho\fR
.IP "" 4
Display your current public IP address


.SH "EXAMPLES"
\fBvswitch protocol udp\fR
.IP "" 4
Set \fBudp\fR as the preferred protocol for connecting to VPNs
.TP
\fBvswitch on\fR
.IP "" 4
Prevent all non-tunneled communications


.
.SH "SEE ALSO"
\fBOpenVPN\fR
.TP
\fBufw\fR


.SH "AUTHOR"
   git clone https://github.com/MorningCoffeeZombie/LinuxVPNKillswitch.git
.
.SH "COPYRIGHT"
    GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
